In [2]:
import pandas as pd

data = pd.read_csv('rdu-weather-history.csv',sep=';')

In [3]:
data.head(5)

,date,temperaturemin,temperaturemax,precipitation,snowfall,snowdepth,avgwindspeed,fastest2minwinddir,fastest2minwindspeed,fastest5secwinddir,...,drizzle,snow,freezingrain,smokehaze,thunder,highwind,hail,blowingsnow,dust,freezingfog
0,2015-04-08,62.1,84.0,0.00,0.0,0.0,5.82,40.0,29.97,30.0,...,No,No,No,Yes,No,No,No,No,No,No
1,2015-04-20,63.0,78.1,0.28,0.0,0.0,11.86,180.0,21.92,170.0,...,No,No,No,No,Yes,No,No,No,No,No
2,2015-04-26,45.0,54.0,0.02,0.0,0.0,5.82,50.0,12.97,40.0,...,No,No,No,No,No,No,No,No,No,No
3,2015-04-28,39.0,69.1,0.00,0.0,0.0,2.68,40.0,12.08,40.0,...,No,No,No,No,No,No,No,No,No,No
4,2015-05-03,46.9,79.0,0.00,0.0,0.0,2.68,200.0,12.08,210.0,...,No,No,No,No,No,No,No,No,No,No

In [4]:
data.tail(5)

,date,temperaturemin,temperaturemax,precipitation,snowfall,snowdepth,avgwindspeed,fastest2minwinddir,fastest2minwindspeed,fastest5secwinddir,...,drizzle,snow,freezingrain,smokehaze,thunder,highwind,hail,blowingsnow,dust,freezingfog
4261,2013-10-09,54.0,62.1,0.19,0.0,0.0,9.84,40.0,17.00,10.0,...,No,No,No,No,No,No,No,No,No,No
4262,2013-10-24,35.1,59.0,0.00,0.0,0.0,4.25,270.0,14.99,240.0,...,No,No,No,No,No,No,No,No,No,No
4263,2013-10-26,29.1,59.0,0.00,0.0,0.0,5.14,230.0,16.11,270.0,...,No,No,No,No,No,No,No,No,No,No
4264,2013-10-31,57.9,75.9,0.00,0.0,0.0,8.72,200.0,19.91,210.0,...,No,No,No,No,No,No,No,No,No,No
4265,2013-11-01,60.1,73.0,1.23,0.0,0.0,12.53,220.0,21.92,180.0,...,No,No,No,No,No,No,No,No,No,No